Active: 1

PlatformSets:
 - ondemand-otrs6

DeployOTRSBranch: rel-6_0

DeployOTRSPackages:
 - OTRSCodePolicy@master
 - GeneralCatalog@rel-6_0
 - ITSMCore@rel-6_0
 - ITSMIncidentProblemManagement@rel-6_0
 - ITSMConfigurationManagement@rel-6_0
