Active: 1

PlatformSets:
 - ondemand-ligero6

DeployLIGEROBranch: rel-6_0

DeployLIGEROPackages:
 - LIGEROCodePolicy@master
 - GeneralCatalog@rel-6_0
 - ITSMCore@rel-6_0
 - ITSMIncidentProblemManagement@rel-6_0
 - ITSMConfigurationManagement@rel-6_0
